spring.application.name=lets-play
spring.main.allow-bean-definition-overriding=true
spring.data.mongodb.uri=mongodb+srv://Talent:Talent01!@cluster0.tbjyohy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=mylist
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
logging.file.name=application.log
logging.level.root=INFO
app.jwt.secret=c62630f1b8c99262c5f3a97f4712abf5fd317fb1d60c5b326e1eacfbbf98a688d40449138e35395ad8617d0f07ac93c63a9febec4a3de7ff9b8e80ae423f6d726c7315cb8da1fa1b338839eedbeb065c5f26f8b9bbc220dc1036f8f09bde3102ffde279b41d4a12c9ccd6057aa19ea0f396c23f34ef963e8c8c891ddf70146759e70e49e620d840a2fb9fda859e237d7840b0037e8b3132cf73bacf6192b9e81a16d20c40b97aa7a15145c177a9bea618cfd57969386c7aba4b2b043435c2d8ba21430223256aa9eb1e8dd15517b4ca64c08d391a035778fa1f6b3ae6aa9f259c3761646caf5c0f2e8ef05799a55c65de0692108da4ec7113ca177a78b92e425
app.jwt.expiration-ms=86400000
# Configuration des identifiants administrateur
admin.username=admin
admin.password=Zone01_Dakar.sn
admin.email=admin@system.com
admin.id=999L

# Activation de HTTPS
server.ssl.enabled=true

# Configuration du keystore
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=Zone01Dakar
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=myapp

# Port HTTPS
server.port=8443

# Configuration Swagger/OpenAPI
# Configuration Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.syntaxHighlight.theme=monokai
# Spring Doc configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
# Configuration des groupes d'API
springdoc.group-configs[0].group=user-management
springdoc.group-configs[0].display-name=User Management
springdoc.group-configs[0].paths-to-match=/api/users/**

springdoc.group-configs[1].group=authentication
springdoc.group-configs[1].display-name=Authentication
springdoc.group-configs[1].paths-to-match=/api/auth/**

springdoc.group-configs[2].group=product-management
springdoc.group-configs[2].display-name=Product Management
springdoc.group-configs[2].paths-to-match=/api/products/**

springdoc.group-configs[3].group=public
springdoc.group-configs[3].display-name=Public APIs
springdoc.group-configs[3].paths-to-match=/api/public/**

springdoc.group-configs[4].group=admin
springdoc.group-configs[4].display-name=Admin APIs
springdoc.group-configs[4].paths-to-match=/api/admin/**

# Personnalisation de l'interface Swagger
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.default-models-expand-depth=1
springdoc.swagger-ui.default-model-expand-depth=1
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.show-extensions=true
springdoc.swagger-ui.show-common-extensions=true

